[project]
name = "resume-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
package-mode = false
dependencies = [
    "openai>=1.84.0",
    "streamlit>=1.45.1",
]
